global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

scrape_configs:
# Example job for node_exporter
  - job_name: 'Node Exporter' # Scrape name
    static_configs:
      - targets: ['node-exporter:9100'] # Node exporter targets
