services:
  app.romm:
    image: rommapp/romm:latest
    container_name: ${app_name:-app_romm}
    environment:
      - DB_HOST=${db_name:-db_romm}
      - DB_NAME=${db_database:-default}
      - DB_USER=${db_user:-default}
      - DB_PASSWD=${db_password:-default}
      - IGDB_CLIENT_ID=${igdb_client_id}
      - IGDB_CLIENT_SECRET=${igdb_client_secret}
      - STEAMGRIDDB_API_KEY=${steamgriddb_api_key}
      - ROMM_AUTH_SECRET_KEY=${romm_auth_secret}
    volumes:
      - romm_redis:/redis-data
      - romm_assets:/romm/assets
      - romm_config:/romm/config
      - romm_libary:/romm/library
      - romm_resources:/romm/resources
#    ports:
#      - 8000:8080
    restart: unless-stopped
    depends_on:
      db.romm:
        condition: service_healthy
    networks:
      net:
        ipv4_address: ${app_ipv4}

  db.romm:
    image: mariadb:latest
    container_name: ${db_name:-db_romm}
    environment:
      - MYSQL_ROOT_PASSWORD=${db_root_password:-rootpassword}
      - MYSQL_DATABASE=${db_database:-defualt}
      - MYSQL_USER=${db_user:-default}
      - MYSQL_PASSWORD=${db_password:-default}
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      net:
        ipv4_address: ${db_ipv4}

volumes:
  mysql_data:
    name: romm.db
  romm_redis:
    name: romm.redis
  romm_assets:
    name: romm.assets
  romm_config:
    name: romm.config
  romm_libary:
    name: romm.libary
  romm_resources:
    name: romm.resources

networks:
  net:
    name: ${network_name}
    external: true
