services:
  mc:
    container_name: ${app_name:-minecraft}
    hostname: ${app_name:-minecraft}
    image: itzg/minecraft-server
    environment:
      TYPE: "VANILLA"
      EULA: "true"
      VERSION: "1.21.4"
      MEMORY: ${server_memory:-1G}
    ports:
      - ${app_port:-25565}:25565
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro # Just to make the time right | you can choose either one or both like me
      - /etc/localtime:/etc/localtime:ro # Just to make the time right
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      net:
        ipv4_address: ${app_ipv4}

volumes:
  data:
    name: minecraft.data

networks:
  net:
    name: ${network_name}
    external: true
