services:
  app.zim:
    container_name: ${app_name}
    image: kiwis/kiswix-serve
#    port:
#      - 80:80
    volumes:
      - ./data:/data
    networks:
      net:
        ipv4_address: ${app_ipv4}

networks:
  net:
    name: ${network_name}
    external: true