services:
  app.kiwix:
    container_name: ${app_name}
    image: ghcr.io/kiwix/kiwix-serve:latest
#    ports:
#      - 80:80
    volumes:
      - ./data:/data
    command:
      - '*'
    networks:
      net:
        ipv4_address: ${app_ipv4}


networks:
  net:
    name: ${network_name}
    external: true
