services:
  app.semaphore:
    container_name: ${APP_NAME:-semaphore}
    restart: ${RESTART_POLICY:-unless-stopped}
    #ports:
    #  - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${DB_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${DB_PASSWORD:-semaphore}
      SEMAPHORE_DB_HOST: ${DB_HOST:-db}
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${DB_TABLE:-semaphore}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-semaphore}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME:-admin}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ACCESS_KEY_ENCRYPTION}
      TZ: ${TZ}
    networks:
      net:
        ipv4_address: ${APP_IPV4}
    depends_on:
      - db.semaphore # for postgres, change to: postgres
  db.semaphore:
    container_name: ${DB_NAME:-semaphore.db}
    restart: ${RESTART_POLICY:-unless-stopped}
    image: mysql:8.0
    hostname: ${DB_NAME:-semaphore.db}
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_TABLE:-semaphore}
      MYSQL_USER: ${DB_USER:-semaphore}
      MYSQL_PASSWORD: ${DB_PASSWORD:-semaphore}
    networks:
      net:
        ipv4_address: ${DB_IPV4}

volumes:
  semaphore-mysql:
    name: semaphore.db

networks:
  net:
    name: ${NETWORK}
    external: true